version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
    - "9092"
    environment:
      HOSTNAME_COMMAND: "getent hosts host.docker.internal | awk '{ print $$1 }'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock